### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by itsgoofer** [markmssd/bitbucket-server-nodejs#12]
Hello, I'm building a simple NodeJS based CLI with some bitbucket features. 

I'm trying to connect using basic auth but I'm struggling with the apis url:

var auth = {
    "type": "basic",
    "username": "username",
    "password": "password"
  }
  
  var client = await new bitbucket('https://api.bitbucket.orgs/2.0', auth)

  client.settings.get('omarfouad')

I'm getting a 'Resource not found' error. 
Ideas?

**Comment by markmssd** [comment]
@omarfouad sorry for the long reply. We're you able to connect?

**Comment by markmssd** [comment]
Feel free to re-open if still an issue.
