### ISSUE TITLE
`client.repos.getAll` compounds results of previous calls

### ISSUE THREAD

**Issue by adrukh** [markmssd/bitbucket-server-nodejs#9]
The implementation of `client.repos.getAll` is not idempotent, and compounds responses from the second call onwards. 
It seems to keep a global state of all repos read (for recursion purposes), requiring the creation of a new client to nullify state.

The culprit is at https://github.com/markmssd/bitbucket-server-nodejs/blob/master/lib/api/repos.js#L10

The following code demonstrates the issue:
```
const client = new Client(url, auth);

client.repos.getAll().then(repos => console.log(repos.length)); // prints N
client.repos.getAll().then(repos => console.log(repos.length)); // prints 2N
```

Can you please comment on this finding? I can submit a quick PR that will add an optional `repos` array as a second arg of `getAll`, allowing the recursion to carry its state internally.

**Comment by markmssd** [comment]
Hey! Sorry for this delayed response and thanks for pointing out this issue.

I have tried it and I can confirm this issue. If you're still willing to submit your PR I would greatly appreciate it!

Thanks :)

**Comment by markmssd** [comment]
@adrukh I have fixed this issue here: https://github.com/markmssd/bitbucket-server-nodejs/commit/4ff4477ab6adaf88b48d37758f51ac0c6140fae3

Thanks for pointing it out!
